server:
  port: 8087

spring:
  application:
    name: vote-service
  jpa:
    database: MYSQL
  datasource:
    url: jdbc:mysql://localhost:3306/vote?createDatabaseIfNotExist=true&serverTimezone=UTC&allowPublicKeyRetrieval=true&useSSL=false
    username: root
    password: springboot
    jpa:
      show-sql: true
      hibernate:
        ddl-auto: none
  kafka:
    bootstrap-servers: localhost:9092

  jackson:
    deserialization:
      fail-on-unknown-properties: true

topic:
  name: topic-vote
api:
  user-info: https://user-info.herokuapp.com/users