server:
  port: 8087

spring:
  application:
    name: vote-service
  jpa:
    database: MYSQL
  datasource:
    url: jdbc:mysql://localhost:3306/vote?createDatabaseIfNotExist=true&serverTimezone=UTC&allowPublicKeyRetrieval=true&useSSL=false
    username: root
    password: springboot
    jpa:
      show-sql: true
      hibernate:
        ddl-auto: none

