CREATE TABLE session (
    id BIGINT(20) PRIMARY KEY AUTO_INCREMENT,
    topic_id BIGINT(20),
    start_date DATETIME NOT NULL,
    end_date DATETIME NOT NULL,
    FOREIGN KEY (topic_id) REFERENCES topic(id)
) ENGINE=InnoDB DEFAULT CHARSET=utf8;